name: Lint files

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-php:
    name: Lint PHP files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Check out the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up PHP
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # 2.30.4
        with:
          coverage: none
        env:
          fail-fast: 'true'

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # 3.0.0
  
      - name: Lint files
        run: composer phpcs
